PLACEHOLDER_IMAGES = [
    "https://images.pexels.com/photos/12217206/pexels-photo-12217206.jpeg?auto=compress&cs=tinysrgb&w=1400",
    "https://images.pexels.com/photos/8706570/pexels-photo-8706570.jpeg?auto=compress&cs=tinysrgb&w=1400",
    "https://images.pexels.com/photos/12579906/pexels-photo-12579906.jpeg?auto=compress&cs=tinysrgb&w=1400",
    "https://images.pexels.com/photos/20493840/pexels-photo-20493840.jpeg?auto=compress&cs=tinysrgb&w=1400",
    "https://images.pexels.com/photos/12320902/pexels-photo-12320902.jpeg?auto=compress&cs=tinysrgb&w=1400",
    "https://images.pexels.com/photos/15064041/pexels-photo-15064041.jpeg?auto=compress&cs=tinysrgb&w=1400",
    "https://images.pexels.com/photos/1457801/pexels-photo-1457801.jpeg?auto=compress&cs=tinysrgb&w=1400",
]

CATEGORIES = [
    {"name": "Gold Jewellery", "slug": "gold-jewellery"},
    {"name": "Bridal Collections", "slug": "bridal-collections"},
    {"name": "Temple Jewellery", "slug": "temple-jewellery"},
    {"name": "Silver Jewellery", "slug": "silver-jewellery"},
    {"name": "Wedding Collections", "slug": "wedding-collections"},
]

PRODUCTS = [
    {
        "name": "Maharani Bridal Necklace",
        "slug": "maharani-bridal-necklace",
        "price": 1299000,
        "category": "Bridal Collections",
        "weight": "78.5g",
        "making_charges": "14%",
        "purity": "22K",
        "stones": "Kundan, Polki accents",
        "stock": 4,
        "images": [PLACEHOLDER_IMAGES[0], PLACEHOLDER_IMAGES[1]],
        "description": "A regal bridal necklace inspired by palace motifs and heirloom Indian craft.",
        "trending": True,
    },
    {
        "name": "Temple Lakshmi Haram",
        "slug": "temple-lakshmi-haram",
        "price": 995000,
        "category": "Temple Jewellery",
        "weight": "61.2g",
        "making_charges": "12%",
        "purity": "22K",
        "stones": "Ruby toned stones",
        "stock": 7,
        "images": [PLACEHOLDER_IMAGES[3], PLACEHOLDER_IMAGES[0]],
        "description": "Traditional temple craft with sculpted goddess motifs and antique finish.",
        "trending": True,
    },
    {
        "name": "Everyday Gold Bangles",
        "slug": "everyday-gold-bangles",
        "price": 507500,
        "category": "Gold Jewellery",
        "weight": "31.8g",
        "making_charges": "10%",
        "purity": "22K",
        "stones": "None",
        "stock": 12,
        "images": [PLACEHOLDER_IMAGES[2], PLACEHOLDER_IMAGES[3]],
        "description": "Minimal gold bangles made for daily elegance and festive layering.",
        "trending": True,
    },
    {
        "name": "Silver Statement Anklets",
        "slug": "silver-statement-anklets",
        "price": 29200,
        "category": "Silver Jewellery",
        "weight": "92g",
        "making_charges": "Fixed",
        "purity": "925 Silver",
        "stones": "Oxidised detailing",
        "stock": 18,
        "images": [PLACEHOLDER_IMAGES[6], PLACEHOLDER_IMAGES[5]],
        "description": "Heritage anklets with a refined oxidised silver finish.",
        "trending": False,
    },
    {
        "name": "Polki Gold Ring",
        "slug": "polki-gold-ring",
        "price": 183500,
        "category": "Gold Jewellery",
        "weight": "11.4g",
        "making_charges": "11%",
        "purity": "22K",
        "stones": "Polki inspired stones",
        "stock": 9,
        "images": [PLACEHOLDER_IMAGES[4], PLACEHOLDER_IMAGES[5]],
        "description": "A premium gold ring with refined stone detailing for weddings and festive gifting.",
        "trending": True,
    },
    {
        "name": "Antique Gold Kada Bangles",
        "slug": "antique-gold-kada-bangles",
        "price": 709000,
        "category": "Wedding Collections",
        "weight": "43.6g",
        "making_charges": "12%",
        "purity": "22K",
        "stones": "Green stone accents",
        "stock": 6,
        "images": [PLACEHOLDER_IMAGES[3], PLACEHOLDER_IMAGES[2]],
        "description": "Traditional kada bangles with antique gold finish and Indian wedding detailing.",
        "trending": True,
    },
]

BANNERS = [
    {
        "title": "Crafting Moments Since 1978",
        "subtitle": "Quality, hallmarked, exquisite designs from RajKamal Jewellers, Jalna.",
        "image": "https://images.pexels.com/photos/12217206/pexels-photo-12217206.jpeg?auto=compress&cs=tinysrgb&w=2200",
        "order": 1,
        "active": True,
    },
    {
        "title": "A Family Craft & Enduring Legacy",
        "subtitle": "By Late Shri Bhagwanji Dayma, serving families with trusted jewellery.",
        "image": "https://images.pexels.com/photos/12579906/pexels-photo-12579906.jpeg?auto=compress&cs=tinysrgb&w=2200",
        "order": 2,
        "active": True,
    },
]
